[language-server.clangd]
command = "clangd"
args = ["--query-driver=/usr/bin/avr-gcc --query-driver=/usr/bin/arm-none-eabi-gcc"]

[language-server.tinymist]
command = "tinymist"
config.exportPdf = "onSave"
